[config]
default_to_workspace = false

[env]
BINARY_NAME = "simpple-vm"
ENTITLEMENTS_PATH = "entitlements.plist"

# Build debug version
[tasks.build]
command = "cargo"
args = ["build"]

# Build release version
[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

# Sign debug binary
[tasks.sign-debug]
condition = { platforms = ["mac"] }
dependencies = ["build"]
env = { BINARY_PATH = "target/debug/${BINARY_NAME}" }
command = "codesign"
args = ["--force", "--sign", "-", "--entitlements", "${ENTITLEMENTS_PATH}", "${BINARY_PATH}"]

# Sign release binary
[tasks.sign-release]
condition = { platforms = ["mac"] }
dependencies = ["build-release"]
env = { BINARY_PATH = "target/release/${BINARY_NAME}" }
command = "codesign"
args = ["--force", "--sign", "-", "--entitlements", "${ENTITLEMENTS_PATH}", "${BINARY_PATH}"]

# Verify debug binary entitlements
[tasks.verify-debug]
condition = { platforms = ["mac"] }
dependencies = ["sign-debug"]
env = { BINARY_PATH = "target/debug/${BINARY_NAME}" }
command = "codesign"
args = ["--display", "--entitlements", "-", "${BINARY_PATH}"]

# Verify release binary entitlements
[tasks.verify-release]
condition = { platforms = ["mac"] }
dependencies = ["sign-release"]
env = { BINARY_PATH = "target/release/${BINARY_NAME}" }
command = "codesign"
args = ["--display", "--entitlements", "-", "${BINARY_PATH}"]

# Build and sign debug (main task)
[tasks.build-and-sign]
dependencies = ["verify-debug"]

# Build and sign release
[tasks.build-release-and-sign]
dependencies = ["verify-release"]

[tasks.default]
alias = "build-and-sign"